services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha-mensa-dev
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./dev/homeassistant/config:/config
      - ./custom_components/mensa:/config/custom_components/mensa:ro
